Add asynchronous loading and removing functionality
openstreetmap/leaflet-osm pull request #38
Opened 2024-07-24 16:05 UTC by nertc

This PR addresses "Map Data checkbox: perhaps use toggle slider instead" issue mentioned in the https://github.com/openstreetmap/openstreetmap-website/issues/4931

Several changes were made to the data loading functionality:

1. Rendering process will be asynchronous. Therefore, there will be no more browser or page freezes (see "Render Video").
2. Removing process will be also asynchronous and there won't be any freezes (see "Remove Video").

- While objects are being rendered, removing won't be triggered until the rendering process is done. After the process, application will check, and it will start removing rendered objects if necessary. The same applies vice versa.

Connected to the PR https://github.com/openstreetmap/openstreetmap-website/pull/5009
Fixes https://github.com/openstreetmap/openstreetmap-website/issues/4931

### Videos:

Render Video

https://github.com/user-attachments/assets/8e11fc5f-1d9c-4458-a5a8-96479627d5ff

Remove Video

https://github.com/user-attachments/assets/0743916d-353e-4717-8600-c74937b6f2fe

2024-09-03 07:35 UTC, nertc commented
This is prerequisite PR for https://github.com/openstreetmap/openstreetmap-website/pull/5009. If this PR is not merged, openstreetmap-website PR can't be merged.

2024-09-03 08:01 UTC, tomhughes requested changes
I'm quite surprised that it's adding and removing the features that is the slow part rather than parsing the XML to get them details but I guess it's because each feature is a separate layer... Seems it's really leaflet that needs to be faster and this is a somewhat ugly workaround :-(

2024-09-03 15:22 UTC, nertc commented
@tomhughes Thank you for review. I'll change indentation. Idea of this PR is to make rendering asynchronous as now it is freezing app and browser. Currently leaflet takes long time for rendering and deleting SVG elements (calculations done on OSM side are quite fast and doesn't take any noticeable time). To increase speed there will be needed changes in the leaflet. Even this PR overrides some of its functionalities (eachLayer, onAdd adnd onRemove) to make it asynchronous.

2024-09-03 17:13 UTC, mmd-osm commented
Regarding XML parsing time, we also have JSON based endpoints which were helpful in other scenarios to speed up parsing in the browser.

2024-09-05 06:58 UTC, nertc commented on leaflet-osm.js
> +          setTimeout(() => layer.addTo(this));
Indentation was updated

2024-09-05 15:45 UTC, tomhughes approved these changes
Thanks - that looks good now.

2024-09-05 15:45 UTC, merged